[browser]
gatherUsageStats = false

[client]
showErrorDetails = true

[server]
runOnSave = true
maxUploadSize = 100

[theme]
base="light"
primaryColor="#4bc3ff"
backgroundColor="#e8e8e0"
secondaryBackgroundColor="#d8d8c7"
